### ISSUE TITLE
FATAL ERROR NCURSES.H No Such File Or Directory

### ISSUE THREAD

**Issue by MikasGhetoo** [Carmudii/GoGABOT-dev#12]

**Comment by Carmudii** [comment]
install this one
-> `apt-get install libncursesw5-dev`
-> `apt-get install libcurl4-gnutls-dev`

**Comment by MikasGhetoo** [comment]
usr/bin/ld: /tmp/ccPcVGe2.o: in function `server::connect(bool)':
server.cpp:(.text+0x155): undefined reference to `HttpClient::get()'
collect2: error: ld returned 1 exit status
