### ISSUE TITLE
uhm, undefined reference 😧 how do you fix this, dude?

### ISSUE THREAD

**Issue by tubbiewubblies** [Carmudii/GoGABOT-dev#9]
![GoGABOT](https://user-images.githubusercontent.com/110443686/184105757-bdb01a8a-18c0-4488-b06a-57514f46a3b9.png)

**Comment by Carmudii** [comment]
Oh dude, you need to install this required, I've been updating the `README.md`
-> `apt-get install libncursesw5-dev`
->  `apt-get install libcurl4-gnutls-dev`

**Comment by tubbiewubblies** [comment]
i already did that, but it's still not working. what should i do? : '((

**Comment by Carmudii** [comment]
can you give log? after did
-> apt-get install libncursesw5-dev
-> apt-get install libcurl4-gnutls-dev

**Comment by tubbiewubblies** [comment]
![GoGABOT](https://user-images.githubusercontent.com/110443686/184105017-ad26e463-1549-4782-87e8-502ad1c84a58.png)
here is it

**Comment by Carmudii** [comment]
and then run `./build.sh`

**Comment by tubbiewubblies** [comment]
![GoGABOT](https://user-images.githubusercontent.com/110443686/184112443-6e5a045f-3d6c-42e5-9150-65c1378c0c07.png)
![GoGABOT](https://user-images.githubusercontent.com/110443686/184114883-3e7a3981-e44a-41c9-9f64-cd9d9f76b20d.png)
^_^

**Comment by Carmudii** [comment]
try this one `g++ -std=c++17 -Ofast -pthread -o GoGABOT enet/callbacks.c enet/compress.c enet/host.c enet/list.c enet/packet.c enet/peer.c enet/protocol.c enet/unix.c enet/win32.c Ui/menu.cpp main.cpp events.cpp gt.cpp playerInventory.cpp server.cpp utils.cpp httpHandler.cpp world.cpp -lncurses -lcurl`

**Comment by tubbiewubblies** [comment]
oh, it says "g++: error: httpHandler.cpp: No such file or directory"
